PREFIXOS:

GE = GERAIS
VE = VENDAS
PE = PERSONALIZADAS
FS = FISCAL
CP = COMPRAS

--GERAIS
Estabelecimento - GEESTAB
Endereço - GEENDERECO (Compartilhado)
Empresa - GEEMPRESA
Parâmetros da empresS por estabelecimento - GEEMPRESAPARAMESTAB
Relacionamento entre empresa e endereço - GEENDEMPRESA
Funcionarios - GEFUNCIONARIOS
Pessoas - GEPESSOA
Endereço - GEPESSOAEND
País, estados e município - GEPAIS, GEESTADO e GEMUNICIPIO / GEPAISBACEN, GEESTADOIBGE, GEMUNICIPIOIBGE
Log - GELOG, GELOGDET                            
Usuários - GEUSUARIOS
Grupo de usuários - GEGRPUSUARIOS
Vinculo entre o usuário e o grupo - GEUSRGRUPO
Permissões - GEPERMIS
 
--VENDAS
Política comercial - VEPOLITICACOM
Tabela de preço - VEPRVENDA, VEPRVENDAPROD
Pedido - VEPEDVENDA, VEITEMPEDIDO, VEPROGVENDA, VEITEMPEDIMP
Forma e condição de pagamento - VEFORMAPGTO, VECONDPGTO, VEDETCONDPGTO

--PERSONALIZADAS
PEEMPRESA
PEPRODUTO

--FISCAL
Produto - FSPRODUTO
Parâmetros do produto por estabelecimento - FSPRODUTOPARAMESTAB
Parâmetros de produção do produto por estabelecimento - FSPRODUTOPCP
Complemento - FSPRODCOMPLEMENTO / FSPRODCOMPLDET

--COMPRAS
Solicitação - CPSOLCMP, CPSOLCMPDET
Cotacao - CPCOTACAO, CPCOTACAOFORNEC, CPCOTACAOVALOR
Pedido - CPPEDCOMPRA, CPPEDCOMPRADET, CPPEDCOMPRAPROG, CPITEMPEDIMP