/*   COLUNAS:
 - CODESTAB
 - ÍNDICE DO ITEM
 - SEQUÊNCIA
 - CODESTABREF
 - INDICEITEMREF
 - SEQUENCIAREF
 - QUANTIDADE
 - VALOR TOTAL
*/

/*    TABELAS:
>FSNFITEM (ITENS DEVOLVIDOS)
>FSNFITEM (ITENS NOTA AGRUPADA)
>FSTIPOMOV
>FSNFAGRUPAMENTOS
*/

/*
O ITEM QUE É A DEVOLUÇÃO VAI TER O CÓDIGO DO TIPO DE MOVIMENTO IGUAL A EF OU IGUAL EOU
O ITEM DEVOLVIDO VAI REFERENCIAR OS ITENS DA NOTA AGRUPADA PELOS CAMPOS REF
E OS ITENS DA NOTA AGRUPADA VAI REFERENCIAR O INDICE DA NOTA AGRUPADA PELO INDICE DA NOTA DE SAIDA
*/