--(ITENS DEVOLVIDOS)
SELECT *
  FROM FSNFITEM;
  
--(ITENS NOTA AGRUPADA)
SELECT *
  FROM FSNFITEM;
  
--(TIPO DE MOVIMENTAÇÃO)
SELECT * 
  FROM FSTIPOMOV
    WHERE CODTIPO LIKE 'EOU';
  
--(AGRUPAMENTO NOTA FISCAL)
SELECT * 
  FROM FSNFAGRUPAMENTOS;
  
  
SELECT FSNFAGRUPAMENTOS.CODESTAB,
       FSNFITEM.INDICEITEM, 
       FSNFITEM.SEQUENCIA, 
       FSNFITEM.CODESTABREF,
       FSNFITEM.INDICEITEMREF,
       FSNFITEM.SEQUENCIAREF,
       FSNFITEM.QUANTIDADE,
       FSNFITEM.VALORTOTAL
  FROM FSNFITEM,
       FSTIPOMOV,
       FSNFAGRUPAMENTOS; 
 

--ITENS DE DEVOLUÇÃO
SELECT *
  FROM FSTIPOMOV,
       FSNFITEM
 WHERE FSTIPOMOV.CODTIPO = FSNFITEM.CODTIPOMOV
   AND CODTIPO LIKE 'EDV'
    OR CODTIPO LIKE 'EOU';
 

SELECT FSNFITEM.CODESTAB,
       FSNFITEM.INDICEITEM,
       FSNFITEM.SEQUENCIA,
       FSNFITEM.CODESTABREF,
       FSNFITEM.INDICEITEMREF,
       FSNFITEM.SEQUENCIAREF,
       FSNFITEM.QUANTIDADE,
       FSNFITEM.VALORTOTAL,
       FSTIPOMOV.CODTIPO
  FROM FSNFITEM,
       FSNFITEM ITEMREF,
       FSTIPOMOV
 WHERE FSTIPOMOV.CODTIPO = FSNFITEM.CODTIPOMOV
   AND (FSTIPOMOV.CODTIPO LIKE 'EDV'
    OR FSTIPOMOV.CODTIPO LIKE 'EOU')
   AND ITEMREF.CODESTAB = FSNFITEM.CODESTABREF
   AND ITEMREF.INDICEITEM = FSNFITEM.INDICEITEMREF
   AND ITEMREF.SEQUENCIA = FSNFITEM.SEQUENCIAREF
   AND ITEMREF.INDICENFSAI IN (SELECT FSNFAGRUPAMENTOS.INDICENFGERADA 
                                 FROM FSNFAGRUPAMENTOS);
                                 
  