CREATE TABLE HACKERS
(
    HACKER_ID INTEGER PRIMARY KEY,
    NAME VARCHAR2(30)
);

CREATE TABLE CHALLENGES
(
    CHALLENGE_ID INTEGER PRIMARY KEY,
    HACKER_ID INTEGER
);


INSERT INTO HACKERS 
    VALUES (5077,'Rose');
    
INSERT INTO HACKERS 
    VALUES (21283,'Angela');
    
INSERT INTO HACKERS 
    VALUES (62743,'Frank');
    
INSERT INTO HACKERS 
    VALUES (88255,'Patrick');
    
INSERT INTO HACKERS 
    VALUES (96196,'Lisa');
    
INSERT ALL
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (61654, 5077)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (58302, 21283)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (40587, 88255)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (29477, 5077)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (1220, 21283)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (69514, 21283)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (46561, 62743)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (58077, 62743)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (18483, 88255)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (76766, 21283)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (52382, 5077)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (74467, 21283)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (33625, 96196)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (26053, 88255)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (42665, 62743)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (12859, 62743)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (70094, 21283)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (34599, 88255)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (54680, 88255)
INTO CHALLENGES (CHALLENGE_ID, HACKER_ID) VALUES (61881, 5077)
SELECT 1 FROM DUAL;


SELECT *
  FROM CHALLENGES;

SELECT * 
  FROM HACKERS;

SELECT HACKERS.HACKER_ID, HACKERS.NAME, COUNT(CHALLENGES.CHALLENGE_ID) AS TOTAL_CHALLENGES
FROM HACKERS, CHALLENGES
WHERE HACKERS.HACKER_ID = CHALLENGES.HACKER_ID
GROUP BY HACKERS.HACKER_ID, HACKERS.NAME
HAVING COUNT(CHALLENGES.CHALLENGE_ID)  <> (SELECT SUBQ.TOTAL_CHALLENGES
                                             FROM (
                                                   SELECT HACKERS.HACKER_ID, HACKERS.NAME, COUNT(CHALLENGES.CHALLENGE_ID) AS TOTAL_CHALLENGES
                                                     FROM HACKERS, CHALLENGES
                                                    WHERE HACKERS.HACKER_ID = CHALLENGES.HACKER_ID
                                                    GROUP BY HACKERS.HACKER_ID, HACKERS.NAME
                                                   )SUBQ
                                           GROUP BY SUBQ.TOTAL_CHALLENGES
                                           HAVING COUNT(*) > 1) 
ORDER BY CASE 
            WHEN COUNT(CHALLENGES.CHALLENGE_ID) THEN HACKERS.HACKER_ID 
            ELSE COUNT(CHALLENGES.CHALLENGE_ID) 
        END DESC;

 
 
 
 
 

