CREATE TABLE STUDENTS
(
    ID INTEGER ,
    NAME VARCHAR(30),
    MARKS INTEGER
);

CREATE TABLE GRADES
(
    GRADE INTEGER,
    MIN_MARK INTEGER,
    MAX_MARK INTEGER
);

INSERT INTO STUDENTS VALUES (1,'JULIA',88);

INSERT INTO STUDENTS VALUES (2,'SAMANTHA',68);

INSERT INTO STUDENTS VALUES (3,'MARIA',99);

INSERT INTO STUDENTS VALUES (4,'SCARLET',78);

INSERT INTO STUDENTS VALUES (5,'ASHLEY',63);

INSERT INTO STUDENTS VALUES (6,'JANE',81);



INSERT INTO GRADES VALUES (1,0,9);

INSERT INTO GRADES VALUES (2,10,19);

INSERT INTO GRADES VALUES (3,20,29);

INSERT INTO GRADES VALUES (4,30,39);

INSERT INTO GRADES VALUES (5,40,49);

INSERT INTO GRADES VALUES (6,50,59);

INSERT INTO GRADES VALUES (7,60,69);

INSERT INTO GRADES VALUES (8,70,79);

INSERT INTO GRADES VALUES (9,80,89);

INSERT INTO GRADES VALUES (10,90,100);


SELECT DISTINCT 
       CASE
          WHEN STUDENTS.MARKS <= 69 THEN 'NULL'
          ELSE STUDENTS.NAME
       END NAME,
       CASE
          WHEN STUDENTS.MARKS >= 0 AND STUDENTS.MARKS <=9 THEN 1
          WHEN STUDENTS.MARKS >= 10 AND STUDENTS.MARKS <=19 THEN 2
          WHEN STUDENTS.MARKS >= 20 AND STUDENTS.MARKS <=29 THEN 3
          WHEN STUDENTS.MARKS >= 30 AND STUDENTS.MARKS <=39 THEN 4
          WHEN STUDENTS.MARKS >= 40 AND STUDENTS.MARKS <=49 THEN 5
          WHEN STUDENTS.MARKS >= 50 AND STUDENTS.MARKS <=59 THEN 6
          WHEN STUDENTS.MARKS >= 60 AND STUDENTS.MARKS <=69 THEN 7
          WHEN STUDENTS.MARKS >= 70 AND STUDENTS.MARKS <=79 THEN 8
          WHEN STUDENTS.MARKS >= 80 AND STUDENTS.MARKS <=89 THEN 9
          WHEN STUDENTS.MARKS >= 90 AND STUDENTS.MARKS <=100 THEN 10
       END AS GRADES,
       STUDENTS.MARKS
  FROM STUDENTS
 ORDER BY GRADES DESC, Name ASC;