/*              TABELAS FSNFAGRUPAMENTOS,FSNFSAIDA,VEPEDVENDA,FSNFITEM,GEEMPRESA

  COLUNAS NOTA UNIFICADA (NOTA QUE EMGLOBA TODAS AS NOTAS PARA TANSPORTADORA), NOTA CLIENTE , VENDEDOR, PEDIDO EMISSÃO, 
           CLIENTE, PRODUTO, QUANT, VALOR UNITARIO, VALOR TOTAL, DEVOLUÇÃO, SALDO                      

*/

--AGRUPAMENTO DE NOTAS
SELECT *
  FROM FSNFAGRUPAMENTOS;

--SAIDAS
SELECT *
  FROM FSNFSAIDA;
  
--PEDIDO DE VENDA
SELECT *
  FROM VEPEDVENDA;

--EMPRESA
SELECT *
  FROM GEEMPRESA;
  
--PRODUTOS
SELECT *
  FROM FSPRODUTO;

--ITENS
SELECT *
  FROM FSNFITEM;
  