CREATE TABLE ActorDirector
(
    ACTOR_ID INTEGER,
    DIRECTOR_ID INTEGER,
    TIMESTAMP INTEGER PRIMARY KEY
);

DROP TABLE ACTORDIRECTOR;

INSERT INTO ACTORDIRECTOR VALUES (1, 1 ,0);
INSERT INTO ACTORDIRECTOR VALUES (1, 1 ,1); 
INSERT INTO ACTORDIRECTOR VALUES (1, 1 ,2); 
INSERT INTO ACTORDIRECTOR VALUES (1, 2 ,3); 
INSERT INTO ACTORDIRECTOR VALUES (1, 2 ,4); 
INSERT INTO ACTORDIRECTOR VALUES (2, 1 ,5); 
INSERT INTO ACTORDIRECTOR VALUES (2, 1 ,6);

SELECT * 
  FROM ACTORDIRECTOR;

SELECT ACTOR_ID "actor_id",
       DIRECTOR_ID "director_id"
  FROM (
         SELECT ACTOR_ID,
                DIRECTOR_ID,
                COUNT (*)
           FROM ACTORDIRECTOR
          GROUP BY ACTOR_ID,DIRECTOR_ID
          HAVING COUNT(*) >= 3
       );