CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    NAME VARCHAR(30),
    SALARY INTEGER
);


INSERT INTO EMPLOYEES VALUES (2,'Meir',3000);

INSERT INTO EMPLOYEES VALUES (3,'Michael',3800);

INSERT INTO EMPLOYEES VALUES (7,'Addilyn',7400);

INSERT INTO EMPLOYEES VALUES (8,'Juan',6100);

INSERT INTO EMPLOYEES VALUES (9,'Kannon',7700);


SELECT EMPLOYEE_ID "employee_id",
       CASE 
            WHEN MOD(EMPLOYEE_id,2) = 1 AND NAME NOT LIKE 'M%' THEN SALARY 
       END AS"bonus"
  FROM EMPLOYEES;       