CREATE TABLE STOCKS
(
    STOCK_NAME VARCHAR(30),
    OPERATION VARCHAR(4),
    OPERATION_DAY INTEGER,
    PRICE INTEGER  
);

ALTER TABLE STOCKS
DROP CONSTRAINT PK_STOCKS_NAME;

ALTER TABLE STOCKS
ADD CONSTRAINT ENUM_STOCKS_OPERATION CHECK (OPERATION IN('Sell','Buy'));

ALTER TABLE STOCKS
ADD CONSTRAINT PK_STOCKS_DAY PRIMARY KEY (OPERATION_DAY);

ALTER TABLE STOCKS
DROP CONSTRAINT PK_STOCKS_DAY;

INSERT INTO STOCKS VALUES ('Leetcode','Buy',1,1000);

INSERT INTO STOCKS VALUES ('Corona Masks','Buy',2,10);

INSERT INTO STOCKS VALUES ('Leetcode','Sell',5,9000);

INSERT INTO STOCKS VALUES ('Handbags','Buy',17,30000);

INSERT INTO STOCKS VALUES ('Corona Masks','Sell',3,1010);

INSERT INTO STOCKS VALUES ('Corona Masks','Buy',4,1000);

INSERT INTO STOCKS VALUES ('Corona Masks','Sell',5,500);

INSERT INTO STOCKS VALUES ('Corona Masks','Buy',6,1000);

INSERT INTO STOCKS VALUES ('Handbags','Sell',29,7000);

INSERT INTO STOCKS VALUES ('Corona Masks','Sell',10,10000);

SELECT * FROM STOCKS;


SELECT  STOCK_NAME "stock_name", 
        SUM( DECODE(OPERATION, 'Sell', PRICE, -PRICE)) "capital_gain_loss" 
  FROM STOCKS 
  GROUP BY STOCK_NAME