CREATE TABLE PRODUCTS 
(
    PRODUCT_ID INTEGER PRIMARY KEY,
    STORE1 INTEGER,
    STORE2 INTEGER,
    STORE3 INTEGER
);

INSERT INTO PRODUCTS VALUES (0,95,100,105);

INSERT INTO PRODUCTS VALUES (1,70,NULL,80);

SELECT *
  FROM PRODUCTS;
  
SELECT PRODUCT_ID,STORE,PRICE
FROM PRODUCTS
UNPIVOT
(
	PRICE
	FOR STORE IN (STORE1 AS 'store1',STORE2 AS 'store2',STORE3 AS 'store3')
);
