CREATE TABLE STADIUM 
(
ID INT,
VISIT_DATE VARCHAR(10) PRIMARY KEY ,
PEOPLE INT
);


INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('1', '2017-01-01', '10');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('2', '2017-01-02', '109');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('3', '2017-01-03', '150');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('4', '2017-01-04', '99');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('5', '2017-01-05', '145');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('6', '2017-01-06', '1455');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('7', '2017-01-07', '199');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('8', '2017-01-09', '188');


SELECT ID FROM STADIUM WHERE 
SELECT PEOPLE - LEAD(PEOPLE) OVER (ORDER BY ID) AS TESTE
  FROM STADIUM;
  
  
SELECT ID, VISIT_DATE  , PEOPLE 
FROM
(
           SELECT * , 
           LEAD(PEOPLEMORETHAN100) OVER (ORDER BY ID) LEAD1,
           LEAD(PEOPLEMORETHAN100,2) OVER(ORDER BY ID) LEAD2,
           LAG(PEOPLEMORETHAN100) OVER(ORDER BY ID) LAG1,
           LAG(PEOPLEMORETHAN100,2) OVER(ORDER BY ID) LAG2
    FROM
    (
        SELECT ID , VISIT_DATE  , PEOPLE ,
               CASE WHEN PEOPLE>= 100
                    THEN 1
                    ELSE 0
                    END AS PEOPLEMORETHAN100
        FROM STADIUM
    ) TEMP
)TEMP1
WHERE (PEOPLEMORETHAN100 = 1 AND LEAD1 = 1 AND LEAD2 = 1)
      OR
      (PEOPLEMORETHAN100 = 1 AND LEAD1 = 1 AND LAG1 =1)
      OR
      (PEOPLEMORETHAN100 = 1 AND LAG1 = 1 AND LAG2 = 1)