CREATE TABLE STADIUM 
(
ID INT,
VISIT_DATE VARCHAR(10) PRIMARY KEY ,
PEOPLE INT
);


INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('1', '2017-01-01', '10');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('2', '2017-01-02', '109');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('3', '2017-01-03', '150');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('4', '2017-01-04', '99');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('5', '2017-01-05', '145');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('6', '2017-01-06', '1455');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('7', '2017-01-07', '199');
INSERT INTO STADIUM (ID, VISIT_DATE, PEOPLE) VALUES ('8', '2017-01-09', '188');

SELECT  ID,
        VISIT_DATE,
        PEOPLE
  FROM (        
         SELECT ID, 
                PEOPLE, 
                VISIT_DATE,
                ABS(PEOPLE - PROX_VALOR) DIF_VALOR_PROX, 
                ABS(PEOPLE - ANTERIOR_VALOR) DIF_VALOR_ANT
           FROM (SELECT ID, 
                        PEOPLE,
                        VISIT_DATE,
                        LEAD(PEOPLE,1,0) OVER (ORDER BY ID) PROX_VALOR,
                        LAG(PEOPLE,1,0) OVER (ORDER BY ID) ANTERIOR_VALOR
                   FROM STADIUM
                )
           WHERE ABS(PEOPLE - PROX_VALOR) >= 100
           OR ABS(PEOPLE - ANTERIOR_VALOR) >= 100
       )
  ORDER BY VISIT_DATE;
 
  
SELECT *
  FROM STADIUM T1, STADIUM T2, STADIUM T3
  WHERE T2.ID - T1.ID = 1
  AND T3.ID - T2.ID = 1;
  
SELECT *
  FROM STADIUM T1, STADIUM T2, STADIUM T3
  WHERE (T1.ID = ((T2.ID+1)-1)) 
  AND ((T2.ID+1) = ((T3.ID+2)-1))

