CREATE TABLE PRODUCTS
(
    product_id INTEGER PRIMARY KEY,
    product_name VARCHAR(30),
    unit_price INTEGER
);

CREATE TABLE SALES
(
    SELLER_ID  INTEGER,
    PRODUCT_ID INTEGER,
    BUYER_ID   INTEGER, 
    SALE_DATE  DATE,
    QUANTITY   INTEGER,
    PRICE      INTEGER  
);

INSERT INTO PRODUCTS VALUES (1,'S8',1000);

INSERT INTO PRODUCTS VALUES (2,'G4',800);

INSERT INTO PRODUCTS VALUES (3,'IPHONE',1400);


SELECT * FROM SALES;

ALTER TABLE SALES;


INSERT INTO SALES VALUES (1,1,1,'21-01-2019',2,2000);

INSERT INTO SALES VALUES (1,2,2,'17/02/2019',1,800);

INSERT INTO SALES VALUES (2,2,3,'02/06/2019',1,800);

INSERT INTO SALES VALUES (3,3,4,'13/05/2019',2,2800);

SELECT DISTINCT P.PRODUCT_ID, P.PRODUCT_NAME
  FROM PRODUCT P, SALES S
  WHERE S.PRODUCT_ID = P.PRODUCT_ID
  AND  S.SALE_DATE BETWEEN TO_DATE('01/01/2019','DD/MM/YYYY') AND TO_DATE('31/03/2019','DD/MM/YYYY')
  AND P.PRODUCT_ID NOT IN (SELECT  P.PRODUCT_ID 
                            FROM PRODUCT P, SALES S 
                           WHERE P.PRODUCT_ID = S.PRODUCT_ID 
                           AND (SALE_DATE < '01/01/2019' OR SALE_DATE > '31/03/2019'));
                           
SELECT *
  FROM SALES;
  
SELECT *
  FROM PRODUCT; 
  