CREATE TABLE TREE 
(
    ID NUMBER(1) PRIMARY KEY,
    P_ID NUMBER(1)
);

INSERT INTO TREE VALUES (1,'');
INSERT INTO TREE VALUES (2,1);
INSERT INTO TREE VALUES (3,1);
INSERT INTO TREE VALUES (4,2);
INSERT INTO TREE VALUES (5,2);

SELECT * FROM TREE;

SELECT ID,
       CASE
          WHEN P_ID IS NULL THEN 'Root'
          WHEN ID IN (SELECT p_id FROM tree) THEN 'Inner'
          ELSE 'Leef'
       END AS TYPE
  FROM TREE;
  
SELECT * FROM TREE;

SELECT ID,P_ID
  FROM TREE
  WHERE ID IN (1);
  
  (SELECT p_id FROM tree);
  
  
  