--GERAIS


--ESTABELECIMENTOS
SELECT *
  FROM GEESTAB;
  
--ENDEREÇOS
SELECT *
  FROM GEENDERECO
  WHERE CODENDERECO <= 10
  ORDER BY CODENDERECO;
  
  
 --RELAÇÃO ENTRE GEESTAB E GEENDERECO
SELECT GTAB.CODESTAB, GTAB.RAZAOSOCIAL,GTAB.NOMEFANTASIA,
       GTAB.CODENDERECO, GEND.CODENDERECO,
       GEND.ENDERECO, GEND.NUMERO, GEND.BAIRRO, GEND.CEP
  FROM GEESTAB GTAB, GEENDERECO GEND
  WHERE GTAB.CODENDERECO = GEND.CODENDERECO;
  
--PARÂMETROS DA EMPRESA POR ESTABELECIMENTO
SELECT * 
  FROM GEEMPRESAPARAMESTAB
  WHERE CODEMPRESA <= 10;
  
--EMPRESA
SELECT *
 FROM GEEMPRESA
 WHERE CODEMPRESA <= 10;

--RELAÇÃO GEEMPRESA COM GEEMPRESAPARAMESTAB
SELECT GEEMPRESA.CODEMPRESA, GEEMPRESA.RAZAOSOCIAL, GEEMPRESA.NOMEFANTASIA,
       GEEMPRESAPARAMESTAB.CODESTAB,GEEMPRESAPARAMESTAB.STATUS,GEEMPRESAPARAMESTAB.TIPOEMPRESA
  FROM GEEMPRESA, GEEMPRESAPARAMESTAB
  WHERE GEEMPRESA.CODEMPRESA = GEEMPRESAPARAMESTAB.CODEMPRESA
  AND GEEMPRESA.CODEMPRESA <=10;
  
 
--RELAÇÃO GEEMPRESA, GEEMPRESAPARAMESTAB E GEESTAB
SELECT GEEMPRESA.CODEMPRESA, GEEMPRESA.RAZAOSOCIAL, GEEMPRESA.NOMEFANTASIA,
       GEEMPRESAPARAMESTAB.STATUS,GEEMPRESAPARAMESTAB.TIPOEMPRESA,GEEMPRESAPARAMESTAB.CODESTAB,
       GEESTAB.RAZAOSOCIAL RAZAO_SOCIAL_ESTAB, GEESTAB.NOMEFANTASIA NOME_FANTASIA_ESTAB,GEESTAB.CODENDERECO
 FROM GEEMPRESA, GEEMPRESAPARAMESTAB, GEESTAB
 WHERE GEEMPRESA.CODEMPRESA = GEEMPRESAPARAMESTAB.CODEMPRESA
 AND GEESTAB.CODESTAB = GEEMPRESAPARAMESTAB.CODESTAB
 AND GEEMPRESA.CODEMPRESA <=10;
 
--RELAÇÃO GEEMPRESA, GEEMPRESAPARAMESTAB, GEESTAB E GEENDERECO
SELECT GEEMPRESA.CODEMPRESA, GEEMPRESA.RAZAOSOCIAL, GEEMPRESA.NOMEFANTASIA,
       GEEMPRESAPARAMESTAB.STATUS,GEEMPRESAPARAMESTAB.TIPOEMPRESA,GEEMPRESAPARAMESTAB.CODESTAB,
       GEESTAB.RAZAOSOCIAL RAZAO_SOCIAL_ESTAB, GEESTAB.NOMEFANTASIA NOME_FANTASIA_ESTAB,GEESTAB.CODENDERECO,
       GEENDERECO.ENDERECO, GEENDERECO.NUMERO, GEENDERECO.BAIRRO, GEENDERECO.CEP
 FROM GEEMPRESA, GEEMPRESAPARAMESTAB, GEESTAB, GEENDERECO
 WHERE GEEMPRESA.CODEMPRESA = GEEMPRESAPARAMESTAB.CODEMPRESA
 AND GEESTAB.CODESTAB = GEEMPRESAPARAMESTAB.CODESTAB
 AND GEENDERECO.CODENDERECO = GEESTAB.CODENDERECO
 AND GEEMPRESA.CODEMPRESA <=10;

--TABELA DE LIGAÇÃO DE EMPRESA COM ENDEREÇO
SELECT *
  FROM GEENDEMPRESA
  WHERE CODEMPRESA <= 10;

--RELAÇÃO ENTRE EMPRESA E ENDEREÇO: GEENDEMPRESA
SELECT * 
  FROM GEEMPRESA,GEENDEMPRESA,GEENDERECO
  WHERE GEEMPRESA.CODEMPRESA = GEENDEMPRESA.CODEMPRESA
  AND GEENDERECO.CODENDERECO = GEENDEMPRESA.CODENDERECO
  AND GEEMPRESA.CODEMPRESA <=10;
  
--FUNCIONARIOS
SELECT *
  FROM GEFUNCIONARIOS
  WHERE CODFUNCIONARIO <= 10;

--PESSOAS
SELECT *
  FROM GEPESSOA
  WHERE CODPESSOA >= 297
  AND CODPESSOA <= 310
  ORDER BY CODPESSOA;
  
--TABELA DE LIGAÇÃO ENDEREÇO COM PESSOAS
SELECT *
  FROM GEPESSOAEND
  WHERE CODPESSOA >= 297
  AND CODPESSOA <= 310;
  
--RELAÇÃO PESSOA COM ENDEREÇO
SELECT PE.CODPESSOA, P.NOME, P.DTNASCIMENTO,
       PE.CODENDERECO, E.ENDERECO, E.NUMERO, E.BAIRRO,
       E.CEP
  FROM GEPESSOA P, GEENDERECO E, GEPESSOAEND PE
  WHERE P.CODPESSOA = PE.CODPESSOA
  AND  E.CODENDERECO = PE.CODENDERECO
  AND P.CODPESSOA >= 297
  AND P.CODPESSOA <= 310;  

--RELAÇÃO PESSOA COM FUNCIONARIO
SELECT GP.CODPESSOA, GP.NOME, GP.SEXO, GP.DTNASCIMENTO,
       GP.NATURALIDADE, GP.PROFISSAO, GF.CODESTAB, GF.CODFUNCIONARIO,
       GF.STATUS, GF.CODUSUARIO
  FROM GEPESSOA GP, GEFUNCIONARIOS GF
  WHERE GP.CODPESSOA = GF.CODPESSOA
  AND GP.CODPESSOA >= 400
  AND GP.CODPESSOA <= 500;

--USUARIOS
SELECT *
  FROM GEUSUARIOS
  WHERE ROWNUM <= 10;

--GRUPO DE USUARIOS
SELECT *
  FROM GEGRPUSUARIOS
  WHERE ROWNUM <=10;
 
--TABELA DE LIGAÇÃO DE USUARIOS COM GRUPO DE USUARIOS
SELECT *
  FROM GEUSRGRUPO; 

--RELAÇÃO ENTRE USUARIOS E GRUPO DE USUARIOS
SELECT U.CODUSUARIO, U.NOME, GU.CODGRPUSR, GU.DESCGRPUSR
  FROM GEUSUARIOS U,GEGRPUSUARIOS GU, GEUSRGRUPO GUU
  WHERE GUU.CODGRPUSR = GU.CODGRPUSR
  AND GUU.CODUSUARIO = U.CODUSUARIO;

--RELAÇÃO PESSOA, FUNCIOANRIO E USUARIO
SELECT GP.CODPESSOA, GP.NOME, GP.SEXO, GP.DTNASCIMENTO,
       GP.NATURALIDADE, GP.PROFISSAO, GF.CODESTAB, GF.CODFUNCIONARIO,
       GF.STATUS, GF.CODUSUARIO, NVL(GU.EMAIL,'NULL') EMAIL, GU.TIPUSUARIO
  FROM GEPESSOA GP, GEFUNCIONARIOS GF, GEUSUARIOS GU
  WHERE GP.CODPESSOA = GF.CODPESSOA
  AND GU.CODUSUARIO = GF.CODUSUARIO
  AND GP.CODPESSOA >= 400
  AND GP.CODPESSOA <= 500
  ORDER BY CODPESSOA;

--PERMISSOES
-- EXEMPLO:
--COD GRUPO  CODCONTRAFORM  CODCONTRPERMIS
--   126	      471	         15	
SELECT *
  FROM GEPERMIS;

--PERMISSOES REFERENTES AS GRUPO 126 - HINO
SELECT *
  FROM GEGRPUSUARIOS
  WHERE CODGRPUSR = 126;
  
--PERMISSÃO N°471 REFERENTE A ALTERAÇÃO DO PEDIDO DE VENDAS
SELECT *
  FROM GECONTR
  WHERE CODCONTR = 471;
  
--PERMISSÃO Nº 15 REFERENTE A VISUALIZAR LOG DO REGISTRO
SELECT *
  FROM GECONTR
  WHERE CODCONTR = 15;
  
--LOG GERAL 
SELECT * FROM GELOG
ORDER BY DATALOG DESC;

--LOG DETALHADO
SELECT * FROM GELOGDET;

--RELAÇAO LOG E LOG DET
SELECT *
  FROM GELOG, GELOGDET
  WHERE GELOG.CODLOG = GELOGDET.CODLOG
  AND ROWNUM <=100
  ORDER BY DATALOG DESC;


--PAISES
SELECT * 
  FROM GEPAIS
  WHERE ROWNUM <= 10;
  
--COD PAISES DE ACORCO COM BANCO CENTRAL
SELECT *
  FROM GEPAISBACEN
  WHERE ROWNUM <= 10;
  
--RELAÇAO PAISES E PAISES BANCO CENTRAL
SELECT *
  FROM GEPAIS, GEPAISBACEN
  WHERE GEPAISBACEN.CODBACEN = GEPAIS.CODBACEN;

--ESTADOS
SELECT * 
  FROM GEESTADO
  WHERE NOME LIKE 'SÃO%';

--COD ESTADOS DE ACORDO COM IBGE
SELECT * 
  FROM GEESTADOIBGE
  WHERE ROWNUM <= 10;  

--RELAÇAO ENTRE ESTADOS E ESTADOS IBGE
SELECT * 
  FROM GEESTADO, GEESTADOIBGE
  WHERE GEESTADOIBGE.CODIBGE = GEESTADO.CODIBGE;
  
--MUNICIPIOS
SELECT * 
  FROM GEMUNICIPIO
  WHERE CODESTADO = 25
  AND NOME LIKE 'LIMEIRA';
  
--COD GIA SP SOBRE ICMS POR MUNICIPIO
SELECT *
  FROM GEMUNICIPIOGIASP
  WHERE NOME LIKE 'LIMEIRA';
 
--MUNICIPIO DE ACORDO COM IBGE
SELECT *
  FROM GEMUNICIPIOIBGE
  WHERE NOME LIKE 'LIMEIRA';
  




--VENDAS

--POLITICA COMERCIAL 
SELECT *
  FROM VEPOLITICACOM;

--PEDIDOS EM ANÁLISE
SELECT *
  FROM VEPEDIDOANALISE
  WHERE ROWNUM <=100
  ORDER BY CODPEDANALISE DESC;
  
--RELAÇÃO POLITICA COMERCIAL E PEDIDO EM ANÁLISE
SELECT VEPEDIDOANALISE.CODPEDVENDA,VEPEDIDOANALISE.CODESTAB ,VEPEDIDOANALISE.CODPEDANALISE, VEPEDIDOANALISE.STATUS,
       VEPOLITICACOM.CODPOLITICA, VEPOLITICACOM.DESCRICAO
  FROM VEPOLITICACOM, VEPEDIDOANALISE
  WHERE VEPOLITICACOM.CODPOLITICA = VEPEDIDOANALISE.CODPOLITICA
  AND ROWNUM <= 100;
  
--PARAMETROS DE POLITICA COMERCIAL POR ESTABELECIMENTO
SELECT *
  FROM VEPOLITICACOMESTAB;
  
--RELAÇÃO PARAMETROS, POLITICA COMERCIAL E ESTABELECIMENTO
SELECT VEPOLITICACOM.CODPOLITICA, VEPOLITICACOM.DESCRICAO, VEPOLITICACOMESTAB.CODESTAB,
       GEESTAB.RAZAOSOCIAL, GEESTAB.NOMEFANTASIA
  FROM VEPOLITICACOM, VEPOLITICACOMESTAB, GEESTAB
  WHERE VEPOLITICACOM.CODPOLITICA = VEPOLITICACOMESTAB.CODPOLITICA
  AND GEESTAB.CODESTAB = VEPOLITICACOMESTAB.CODESTAB;

--TABELA DE PREÇO DE VENDA
SELECT * 
  FROM VEPRVENDA;
  --WHERE CODPRVENDA = 172;

--TABELA DE PREÇO DE VENDA DA PRODUÇÃO
SELECT * 
  FROM VEPRVENDAPROD
  WHERE ROWNUM <= 100;
  
  
--
SELECT *
  FROM VEPRVENDA, VEPRVENDAPROD
  WHERE VEPRVENDA.CODPRVENDA = VEPRVENDAPROD.CODPRVENDA;  

--PEDIDO DE VENDA
SELECT *
  FROM VEPEDVENDA
  WHERE ROWNUM <= 100
  ORDER BY CODESTAB, DATAEMISSAO DESC;

--ITEM DO PEDIDO
SELECT * 
  FROM VEITEMPEDIDO;
  
--PROGRAMAÇÃO DE VENDA
SELECT * 
  FROM VEPROGVENDA;

--IMPOSTO SOBRE ITEM 
SELECT * 
  FROM VEITEMPEDIMP;
 
--FORMA DE PAGAMENTO
SELECT *
  FROM VEFORMAPGTO;
 
SELECT * 
  FROM VECONDPGTO;
  
SELECT *
  FROM VEFORMAPGTO,  VECONDPGTO
  WHERE VEFORMAPGTO.CODFORMAPGTO = VECONDPGTO.CODFORMAPGTO
  ORDER BY VEFORMAPGTO.DATAMODIFICACAO DESC;